os: osx
osx_image: xcode9.2

language: objective-c
xcode_workspace: iGlyph.xcworkspace
xcode_scheme: iGlyph


script:
    - xcodebuild test -workspace iGlyph.xcworkspace -scheme iGlyphTests -destination 'platform=OS X,arch=x86_64' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
